[package]
name        = "arama-sidecar"
description = "External ffmpeg toolchain discovery and probing for arama"
readme      = "../../../README.md"
version.workspace       = true
edition.workspace       = true
rust-version.workspace  = true
authors.workspace       = true
license.workspace       = true
repository.workspace    = true
categories.workspace    = true
keywords.workspace      = true

[dependencies]
arama-env                   = { workspace = true }

anyhow                      = { workspace = true }
command-group               = { workspace = true }
libc                        = { workspace = true }
tokio                       = { workspace = true, features = ["rt"] }
